"""prescription

Revision ID: eace6f150fad
Revises: 0107de9e4473
Create Date: 2024-05-02 18:57:21.210321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eace6f150fad'
down_revision = '0107de9e4473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_medicines')
    op.drop_table('medicines')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               nullable=False)

    op.create_table('medicines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('dosage', sa.VARCHAR(length=64), nullable=False),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription_medicines',
    sa.Column('prescription_id', sa.INTEGER(), nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('prescription_id', 'medicine_id')
    )
    # ### end Alembic commands ###
